### PR TITLE
delete records individually for safety

### PR DESCRIPTION
**Pull request by kmei3560**
This PR changes the logic for the DeleteRecords() method so that it will now iterate through eligible records and send a separate API call to GoDaddy for each delete request. This change should be 100% compatible with the former logic. Additionally I have verified correct functionality in a bulk rotation tool that I use.

The previous logic would identify the slice of "remainder records" based on the user's request to eliminate a subset, and then send this slice of "remainder records" in one API call to GoDaddy. If that single GoDaddy call fails or has any problem, it could result in a disaster situation where large groups of records become missing. My thought is that with the atomic-style single deletes, the risk is reduced and specific to the delete records. This also leaves the "remainder records" alone which is safer (after all, those are the records you never intended to change at all).

Please feel free to critique or let me know if I've done anything wrong here. I apologize that I'm new to Github.
Thank you

### CODE REVIEW

**Comment by mholt** [comment]
Welcome to GitHub, and thank you for the patch!

I'll leave this for @artknight to review when they have a chance :)

**Comment by kmei3560** [comment]
Hi @artknight please let me know if you have any thoughts about these proposed changes. Happy to make any adjustments if you like. Thank you

**Comment by mholt** [comment]
If @artknight is too busy, we can help relieve some of that burden if @kmei3560 would be interested in helping to maintain this repository. Just let me know if you're interested!

**Comment by kmei3560** [comment]
Absolutely, I would love to help maintain this repo. I am also a long-time Godaddy user (I have some domains I'm HODL'ing). Thank you

**Comment by artknight** [comment]
> Absolutely, I would love to help maintain this repo. I am also a long-time Godaddy user (I have some domains I'm HODL'ing). Thank you

Sorry just now reading the messages. Yeah I am good with having another maintainer 😁

**Pull request merged**
