### PR TITLE
Add missing JSON tag

### PR DESCRIPTION
**Pull request by damnever**
I will send another PR to https://github.com/caddy-dns/godaddy after this gets merged.

### CODE REVIEW

**Comment by damnever** [comment]
@artknight please take a look.

**Comment by mholt** [comment]
(Ping me if @artknight is too busy to reply, I will merge it if helpful -- thanks!)

**Comment by artknight** [comment]
@damnever merged.

**Comment by mholt** [comment]
Thank you for maintaining this!

**Pull request merged**
